name: Build and Publish Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build binary
        working-directory: ./src
        run: |
          pyinstaller --onefile --hidden-import=click layergen.py

      - name: Move binary to root directory
        run: |
          mv src/dist/* ./layergen

      - name: Checkout prod branch and reset to remove all files except binary
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b prod || git checkout prod
          git rm -rf . 
          git reset -- .
          mv layergen ./
          git add layergen
          git commit -m "Deploy binary to base directory"

      - name: Push to prod branch
        run: |
          git push origin prod --force
